yml changes

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -31,6 +31,19 @@ jobs:
           distribution: temurin
           java-version: 17
 
+      - name: Create ENV File
+        run: |
+          echo "${{ secrets.ENV_FILE }}" > .env
+
+      - name: Verify ENV File Exists
+        run: |
+          if [ -f .env ]; then
+            echo ".env file created successfully"
+          else
+            echo ".env file missing"
+            exit 1
+          fi
+
       - name: Install Dependencies
         run: yarn install --frozen-lockfile
 
